# Generated by Django 5.1.1 on 2024-10-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mentor",
            name="school",
        ),
        migrations.AddField(
            model_name="mentor",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
