# Generated by Django 5.1.1 on 2025-06-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='other_names',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
