# Generated by Django 5.1.1 on 2024-10-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_mentor_school_mentor_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="school_mentor",
            new_name="mentor",
        ),
    ]
