# Generated by Django 5.1.1 on 2024-10-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_internschool_city_remove_internschool_town_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="intern_account",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="supervisor_account",
        ),
        migrations.AddField(
            model_name="customuser",
            name="account_type",
            field=models.CharField(
                choices=[("intern", "Intern"), ("supervisor", "Supervisor")],
                max_length=50,
                null=True,
            ),
        ),
    ]
