# Generated by Django 5.1.1 on 2024-11-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_customuser_intern_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="title",
            field=models.CharField(
                choices=[
                    ("mr", "Mr."),
                    ("mrs", "Mrs."),
                    ("miss", "Miss"),
                    ("dr", "Dr."),
                    ("prof", "Prof."),
                    ("rev", "Rev."),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
