# Generated by Django 5.1.1 on 2024-12-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_customuser_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="internschool",
            name="address",
        ),
        migrations.RemoveField(
            model_name="internschool",
            name="name",
        ),
        migrations.AddField(
            model_name="internschool",
            name="school",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
