# Generated by Django 5.1.1 on 2024-12-31 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0009_remove_internschool_address_remove_internschool_name_and_more",
        ),
        ("internships", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="cohort",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="internships.cohort",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="level",
            field=models.CharField(max_length=25, null=True),
        ),
    ]
