# Generated by Django 5.1.1 on 2024-12-31 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_customuser_cohort_customuser_level"),
        ("internships", "0005_alter_cohort_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="cohort",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cohort_interns",
                to="internships.cohort",
            ),
        ),
    ]
