# Generated by Django 5.1.1 on 2025-02-28 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_customuser_cohort"),
        ("internships", "0006_alter_cohort_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="cohort",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cohort_interns",
                to="internships.cohort",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="level",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
