# Generated by Django 5.1.1 on 2025-04-08 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_customuser_cohort_alter_customuser_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="intern_school",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="mentor",
        ),
    ]
