# Generated by Django 5.1.1 on 2024-12-31 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=20)),
                ("start_date", models.DateField(auto_now_add=True)),
                (
                    "end_date",
                    models.DateField(
                        default=datetime.datetime(2025, 4, 30, 12, 10, 22, 51375)
                    ),
                ),
            ],
        ),
    ]
