# Generated by Django 5.1.1 on 2024-12-31 12:41

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internships", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohort",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 4, 30, 12, 41, 21, 681032, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="cohort",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="cohort",
            name="year",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
