# Generated by Django 5.1.1 on 2025-06-03 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 10, 1, 23, 11, 7, 639801)),
        ),
    ]
