# Generated by Django 5.1.1 on 2024-12-31 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internships", "0002_alter_cohort_end_date_alter_cohort_start_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohort",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(2025, 4, 30, 12, 45, 10, 338740)
            ),
        ),
    ]
