# Generated by Django 5.1.1 on 2024-12-31 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internships", "0003_alter_cohort_end_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cohort",
            options={"ordering": ["year", "start_date"]},
        ),
        migrations.AlterField(
            model_name="cohort",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(2025, 4, 30, 20, 40, 44, 714971)
            ),
        ),
    ]
