# Generated by Django 5.1.1 on 2025-06-10 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_alter_cohort_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 10, 8, 9, 27, 21, 422040)),
        ),
    ]
