# Generated by Django 5.1.1 on 2024-12-31 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internships", "0004_alter_cohort_options_alter_cohort_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohort",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(2025, 4, 30, 21, 12, 36, 224127)
            ),
        ),
    ]
