# Generated by Django 5.1.1 on 2025-07-04 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0004_alter_cohort_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cohort',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ongoing', max_length=20),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 1, 21, 1, 50, 913050)),
        ),
    ]
