# Generated by Django 5.1.1 on 2025-02-28 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internships", "0005_alter_cohort_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohort",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(2025, 6, 28, 11, 44, 12, 291715)
            ),
        ),
    ]
