# Generated by Django 5.1.1 on 2025-07-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0005_cohort_active_cohort_status_alter_cohort_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
