# Generated by Django 5.1.1 on 2025-05-28 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internships", "0006_alter_cohort_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohort",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(2025, 9, 25, 7, 42, 7, 39494)
            ),
        ),
    ]
