# Generated by Django 5.1.1 on 2024-10-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfoliofile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("teaching_philosophy", "Teaching Philosophy"),
                    ("reflective_writing", "Reflective writing"),
                ],
                default="file",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="portfoliofile",
            name="file",
            field=models.FileField(upload_to="documents/"),
        ),
    ]
