# Generated by Django 5.1.1 on 2025-06-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliofile',
            name='file_type',
            field=models.CharField(choices=[('teaching_philosophy', 'Teaching Philosophy'), ('reflective', 'Reflective Teaching Statement'), ('cv', 'Curriculum Vitae (CV)')], default='file', max_length=50),
        ),
    ]
