# Generated by Django 5.1.1 on 2025-08-26 08:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_comment_content_alter_portfoliofile_file_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('portfolio_month_1', models.DecimalField(blank=True, decimal_places=2, help_text='Score out of 20', max_digits=5, null=True)),
                ('portfolio_month_2', models.DecimalField(blank=True, decimal_places=2, help_text='Score out of 20', max_digits=5, null=True)),
                ('portfolio_month_3', models.DecimalField(blank=True, decimal_places=2, help_text='Score out of 20', max_digits=5, null=True)),
                ('portfolio_month_4', models.DecimalField(blank=True, decimal_places=2, help_text='Score out of 40', max_digits=5, null=True)),
                ('teaching_philosophy_score', models.DecimalField(blank=True, decimal_places=2, help_text='Score out of 100', max_digits=5, null=True)),
                ('reflective_practice_score', models.DecimalField(blank=True, decimal_places=2, help_text='Score out of 100', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_interns', to=settings.AUTH_USER_MODEL)),
                ('intern', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submissions_intern_grade',
            },
        ),
    ]
