# Generated by Django 5.1.1 on 2024-10-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0002_portfoliofile_file_type_alter_portfoliofile_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfoliofile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("teaching_philosophy", "Teaching Philosophy"),
                    ("reflective_writing", "Reflective writing"),
                    ("cv", "Curriculum Vitae (CV)"),
                ],
                default="file",
                max_length=50,
            ),
        ),
    ]
