# Generated by Django 5.1.1 on 2025-07-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_comment_content_alter_portfoliofile_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliofile',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='image',
            field=models.ImageField(upload_to='portfolio_imgs/%Y/%m/%d/'),
        ),
    ]
