# Generated by Django 5.1.1 on 2024-11-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0004_submission_graded_alter_submission_intern_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="grade",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
