# Generated by Django 5.1.1 on 2024-12-31 20:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0008_remove_notification_sender_notification_read_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
