# Generated by Django 5.1.1 on 2025-05-28 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0009_submission_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video",
                        to="submissions.submission",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Grade",
        ),
    ]
